pipelines:
  default:
    - step:
        caches:
          - node
        script:
            - npm install -g @angular/cli
            - npm install -g firebase-tools
            - npm install
            - ng build
            - firebase deploy --only hosting --token "1//0dsN9YYPq8NHuCgYIARAAGA0SNwF-L9Ir82cTCOOSQ4mcd8KMwfjzE033gMkjHyqq522x1ytLZPBsvFK48Ar4A6nixHCyr_mP8vU" --public dist

